export const flashcards = [
    {english: "Dog", german: "Hund"},
    {english: "Cat", german: "Katze"},
    {english: "Bird", german: "Vogel"},
    {english: "Fish", german: "Fisch"},
    {english: "Ridiculous", german: "Lächerlich"},
    {english: "To Eat", german: "Essen"},
    {english: "To Drink", german: "Trinken"},
    {english: "To Go", german: "Gehen"},
    {english: "Bread", german: "Brot"},
    {english: "Apple", german: "Apfel"},
    {english: "Water", german: "Wasser"},
    {english: "Red", german: "Rot"},
    {english: "Here", german: "Hier"},
    {english: "Brother", german: "Bruder"},
  ]